### ISSUE TITLE
Удаление места

### ISSUE THREAD

**Issue by Flerki** [Flerki/home-helper#10]

**Comment by Qwadr** [comment]
Реализовано на сервере
RequestMethod.DELETE, URL = "/place/{placeId}"
Если места с таким placeId не существовало, вернет HttpStatus.NOT_FOUND 404
Если место с таким placeId существовало, удалит его из базы и вернет HttpStatus.NO_CONTENT 204

**Comment by Flerki** [comment]
на фронте готово, но без обработки ошибок
