### ISSUE TITLE
Аутентификация  (обработка пользователя с ошибочными данными)

### ISSUE THREAD

**Issue by Flerki** [Flerki/home-helper#20]
добавить обработку того, что пользователя с предоставленными данными нет

**Comment by Qwadr** [comment]
Сделано.
Если все в порядке, возвращает (Genson().serialize(person), HttpStatus.ACCEPTED (202)).
Если данные ошибочны, возвращает "Can't login: username/password combination is incorrect." и HttpStatus.BAD_REQUEST (400)
