### ISSUE TITLE
Логика удаления места на сервере

### ISSUE THREAD

**Issue by Flerki** [Flerki/home-helper#29]
Не тривиальна, так как на место ссылаются вещи - не дают удалить место:
если  вещь принадлежит какому-либо пользователю, то следует ей в поле place поставить нулл, а если не принадлежит никакому пользователю, то стоит спросить у удаляющего, что с ней делать (привязать к нему или удалить на совсем - пока что стоит просто удалять)

**Comment by Qwadr** [comment]
сделано с простым удалением вещи из базы
