### ISSUE TITLE
Удаление вещи

### ISSUE THREAD

**Issue by Flerki** [Flerki/home-helper#8]

**Comment by Qwadr** [comment]
Сделано на серверной стороне.
DELETE запрос на /thing/{thingId}
Если вещь с таким thingId существовала, она удаляется и высылается HTTP.NO_CONTENT 204
Если вещи с таким thingId не существовала, высылается HTTP.NOT_FOUND 404

**Comment by Qwadr** [comment]
Сделано на серверной стороне.
DELETE запрос на /thing/{thingId}
Если вещь с таким thingId существовала, она удаляется и высылается HTTP.NO_CONTENT 204
Если вещи с таким thingId не существовала, высылается HTTP.NOT_FOUND 404

**Comment by Flerki** [comment]
на фронте готово, но без обработки ошибок пока что
